# Site settings
author: Adi Skop 
title: Why did I become a software engineer
header-img: img/home-bg.png
email: adiskop@gmail.com
copyright_name: Adi Skop 
description: > # this means to ignore newlines until "baseurl:"
  This is my blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  adiskop

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
